"""modified model cofe 2.0

Revision ID: 084089f49ee1
Revises: 20a1e8e6b1b1
Create Date: 2025-12-16 22:03:04.958391

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "084089f49ee1"
down_revision: Union[str, Sequence[str], None] = "20a1e8e6b1b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cofe",
        sa.Column(
            "product_name", sa.String(length=250), nullable=True, comment="Продукт"
        ),
    )
    op.add_column(
        "cofe",
        sa.Column(
            "cover_name", sa.String(length=250), nullable=True, comment="Тип упаковки"
        ),
    )
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        comment="",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    op.drop_column("cofe", "cover_name")
    op.drop_column("cofe", "product_name")
    # ### end Alembic commands ###
