"""modified model cofe - not nan

Revision ID: 20a1e8e6b1b1
Revises: 7aa7db4fde2d
Create Date: 2025-12-16 19:15:26.674778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "20a1e8e6b1b1"
down_revision: Union[str, Sequence[str], None] = "7aa7db4fde2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "city_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        existing_comment="Город продажи",
    )
    op.alter_column(
        "cofe",
        "shop_type_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        existing_comment="Тип торговой точки",
    )
    op.alter_column(
        "cofe",
        "network_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        existing_comment="Название торговой сети",
    )
    op.alter_column(
        "cofe",
        "brand_owner_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        existing_comment="Название бренда кофе",
    )
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        comment="",
    )
    op.alter_column(
        "cofe",
        "subbrand_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        existing_comment="Вкус кофе",
    )
    op.alter_column(
        "cofe",
        "garbage_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=True,
        existing_comment="Состояние (растворимый, 3в1 и т.д.",
    )
    op.alter_column(
        "cofe",
        "quantity",
        existing_type=mysql.INTEGER(),
        nullable=True,
        existing_comment="Количество",
    )
    op.alter_column(
        "cofe",
        "price",
        existing_type=mysql.FLOAT(),
        nullable=True,
        existing_comment="Цена",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "price",
        existing_type=mysql.FLOAT(),
        nullable=False,
        existing_comment="Цена",
    )
    op.alter_column(
        "cofe",
        "quantity",
        existing_type=mysql.INTEGER(),
        nullable=False,
        existing_comment="Количество",
    )
    op.alter_column(
        "cofe",
        "garbage_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        existing_comment="Состояние (растворимый, 3в1 и т.д.",
    )
    op.alter_column(
        "cofe",
        "subbrand_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        existing_comment="Вкус кофе",
    )
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        comment=None,
        existing_comment="",
    )
    op.alter_column(
        "cofe",
        "brand_owner_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        existing_comment="Название бренда кофе",
    )
    op.alter_column(
        "cofe",
        "network_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        existing_comment="Название торговой сети",
    )
    op.alter_column(
        "cofe",
        "shop_type_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        existing_comment="Тип торговой точки",
    )
    op.alter_column(
        "cofe",
        "city_name",
        existing_type=mysql.VARCHAR(length=250),
        nullable=False,
        existing_comment="Город продажи",
    )
    # ### end Alembic commands ###
