"""modified model cofe

Revision ID: 4724ebc32f94
Revises: 573ad6d20b62
Create Date: 2025-12-16 18:44:37.331942

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4724ebc32f94"
down_revision: Union[str, Sequence[str], None] = "573ad6d20b62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "cofe",
        "quantity",
        existing_type=mysql.VARCHAR(length=250),
        type_=sa.Integer(),
        existing_comment="Количество",
        existing_nullable=False,
    )
    op.alter_column(
        "cofe",
        "price",
        existing_type=mysql.VARCHAR(length=250),
        type_=sa.Float(),
        existing_comment="Цена",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "price",
        existing_type=sa.Float(),
        type_=mysql.VARCHAR(length=250),
        existing_comment="Цена",
        existing_nullable=False,
    )
    op.alter_column(
        "cofe",
        "quantity",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(length=250),
        existing_comment="Количество",
        existing_nullable=False,
    )
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
