"""Create model cofe

Revision ID: 573ad6d20b62
Revises:
Create Date: 2025-12-16 17:57:30.313571

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "573ad6d20b62"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cofe",
        sa.Column("id", sa.String(250), nullable=False),
        sa.Column("city_name", sa.String(250), nullable=False, comment="Город продажи"),
        sa.Column(
            "shop_type_name",
            sa.String(250),
            nullable=False,
            comment="Тип торговой точки",
        ),
        sa.Column(
            "network_name",
            sa.String(250),
            nullable=False,
            comment="Название торговой сети",
        ),
        sa.Column(
            "brand_owner_name",
            sa.String(250),
            nullable=False,
            comment="Название бренда кофе",
        ),
        sa.Column("brand_name", sa.String(250), nullable=False, comment=""),
        sa.Column("subbrand_name", sa.String(250), nullable=False, comment="Вкус кофе"),
        sa.Column(
            "garbage_name",
            sa.String(250),
            nullable=False,
            comment="Состояние (растворимый, 3в1 и т.д.",
        ),
        sa.Column("quantity", sa.String(250), nullable=False, comment="Количество"),
        sa.Column("price", sa.String(250), nullable=False, comment="Цена"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cofe")
    # ### end Alembic commands ###
