"""modified model cofe field id

Revision ID: 7aa7db4fde2d
Revises: 4724ebc32f94
Create Date: 2025-12-16 19:00:39.488386

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7aa7db4fde2d"
down_revision: Union[str, Sequence[str], None] = "4724ebc32f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "id",
        existing_type=mysql.VARCHAR(length=250),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        comment="",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cofe",
        "brand_name",
        existing_type=mysql.VARCHAR(length=250),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "cofe",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(length=250),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
