"""modified model cofe 3.0

Revision ID: 85f160193f76
Revises: 084089f49ee1
Create Date: 2025-12-17 18:08:00.371942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "85f160193f76"
down_revision: Union[str, Sequence[str], None] = "084089f49ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coffee",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "city_name", sa.String(length=250), nullable=True, comment="Город продажи"
        ),
        sa.Column(
            "shop_type_name",
            sa.String(length=250),
            nullable=True,
            comment="Тип торговой точки",
        ),
        sa.Column(
            "network_name",
            sa.String(length=250),
            nullable=True,
            comment="Название торговой сети",
        ),
        sa.Column(
            "brand_owner_name",
            sa.String(length=250),
            nullable=True,
            comment="Название бренда кофе",
        ),
        sa.Column("brand_name", sa.String(length=250), nullable=True),
        sa.Column(
            "subbrand_name", sa.String(length=250), nullable=True, comment="Вкус кофе"
        ),
        sa.Column(
            "garbage_name",
            sa.String(length=250),
            nullable=True,
            comment="Состояние (растворимый, 3в1 и т.д.",
        ),
        sa.Column(
            "product_name", sa.String(length=250), nullable=True, comment="Продукт"
        ),
        sa.Column("quantity", sa.Integer(), nullable=True, comment="Количество"),
        sa.Column("price", sa.Float(), nullable=True, comment="Цена"),
        sa.Column(
            "cover_name", sa.String(length=250), nullable=True, comment="Тип упаковки"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("cofe")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cofe",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "city_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Город продажи",
        ),
        sa.Column(
            "shop_type_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Тип торговой точки",
        ),
        sa.Column(
            "network_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Название торговой сети",
        ),
        sa.Column(
            "brand_owner_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Название бренда кофе",
        ),
        sa.Column("brand_name", mysql.VARCHAR(length=250), nullable=True),
        sa.Column(
            "subbrand_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Вкус кофе",
        ),
        sa.Column(
            "garbage_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Состояние (растворимый, 3в1 и т.д.",
        ),
        sa.Column(
            "quantity",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Количество",
        ),
        sa.Column("price", mysql.FLOAT(), nullable=True, comment="Цена"),
        sa.Column(
            "product_name", mysql.VARCHAR(length=250), nullable=True, comment="Продукт"
        ),
        sa.Column(
            "cover_name",
            mysql.VARCHAR(length=250),
            nullable=True,
            comment="Тип упаковки",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("coffee")
    # ### end Alembic commands ###
